### ISSUE TITLE
Workflow Details Overlay throws an error

### ISSUE THREAD

**Issue by ocodia** [umbraco/Umbraco.Workflow.Issues#12]
When you click 'Details' on a task in the 'Tasks requiring my approval' list, the details button spins indefinitely, no overlay is shown and there is an Umbraco Backoffice JS error in the console.

`TypeError: Cannot read properties of undefined (reading 'find')
`

Reproduction
------------

    * Go to Content section
    * Go to WorkFlow tab
    * Click 'Details' on any Task requiring approval
    * See console error

![image](https://user-images.githubusercontent.com/1395678/223731533-46195298-2348-4a6d-af76-68ab89f7c2e5.png)

**Comment by nathanwoulfe** [comment]
Hey @ocodia that is indeed a bug introduced in the dot-one release. I've fixed it, will have a patch out shortly.

**Comment by nathanwoulfe** [comment]
And done - patch is on Nuget now => https://www.nuget.org/packages/Umbraco.Workflow
