### ISSUE TITLE
Workflow Notifications Target is inaccessible

### ISSUE THREAD

**Issue by TQ-Benji** [umbraco/Umbraco.Workflow.Issues#13]
A brief description of the issue goes here.

In the [docs ](https://docs.umbraco.com/umbraco-workflow/getting-started/notifications) it mentions a Target property on a bunch of Notification objects but this property is protected and can't be used

eg WorkflowInstanceCompletedNotification has a Target of IWorkflowInstance which contains properties like NodeId which would be useful to have access to.

Other notifications in the CMS like ContentPublishedNotification expose the Target property with another property eg PublishedEntities

When debugging the handler you can see the Target property and its data but can't use it.

Reproduction
------------

Create a notification handler follow the steps in - https://docs.umbraco.com/umbraco-cms/reference/notifications for one of the notifications that has a Target property and try to access data inside it.

### Expected result

To be able to access the data in a Target property

### Actual result

can not access the Target property due to its protection level

**Comment by nathanwoulfe** [comment]
Hey @TQ-Benji, this is due to Workflow's notifications inheriting from Umbraco's `ObjectNotifcation` for non saved/saving notifications. Saved/saving exposes Target on SavedEntities, but `ObjectNotification`, as you've found, doesn't do similar.

I'll update the affected Workflow notifications to add a public property

**Comment by nathanwoulfe** [comment]
@TQ-Benji x.x.2 patches are on NuGet now, this issue should be fixed.
