### ISSUE TITLE
Workflow and Linux

### ISSUE THREAD

**Issue by NC-RVSO** [umbraco/Umbraco.Workflow.Issues#14]
Hello there :)
I am playing around with Umbraco 10 and a Linux Docker container and thought I would try out Workflow. 
This however turned out to be rather difficult and you had me rather puzzled to what was wrong, but I found the bug for you:
The errors I got was:
![image](https://user-images.githubusercontent.com/91662666/225301262-eb90bbcc-334b-4666-a328-95417cc07b03.png)
And after looking around I noticed the small b in backoffice, as Linux are taken capital letters seriously this will not work as the folder is called Backoffice!
I tried simply renaming the folder and that made me able to access the html but unfortunately the css have been given the capital B.... Renaming a couple of times and utilizing that the browser caches html pages I actually got into the correct page:
![image](https://user-images.githubusercontent.com/91662666/225302088-4c47d5e7-41e3-4bf2-bf96-e906e63df5a4.png)
Meaning: I am fairly certain this is the underlying issue :) 
Will you look into it asap? I would be nice to be able to showcase Workflow inside my container and not having to use ISS :P

**Comment by NC-RVSO** [comment]
For now I have made a hack (Thanks chat-gpt):
`    public class BackofficeRewriteRule : IRule
    {
        public void ApplyRule(RewriteContext context)
        {
            var request = context.HttpContext.Request;
            var path = request.Path.Value;

            // Check if the path contains the incorrect case-sensitive folder name
            if (path.Contains("/App_Plugins/Workflow/backoffice", StringComparison.OrdinalIgnoreCase))
            {
                // Replace the incorrect folder name with the correct one
                var newPath = path.Replace("/App_Plugins/Workflow/backoffice", "/App_Plugins/Workflow/Backoffice", StringComparison.OrdinalIgnoreCase);

                // Update the request path with the correct folder name
                request.Path = newPath;
            }
        }
    }`
This is added in configure:

`    public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
    {
        // HACK should be removed 
        var rewriteOptions = new RewriteOptions().Add(new BackofficeRewriteRule());
        app.UseRewriter(rewriteOptions);`

**Comment by nathanwoulfe** [comment]
Heya @NC-RVSO I thought I'd found all the casing discrepancies, obviously not 😄 

I'll fix this up for the next patch (no date as yet, and given your workaround, this fix isn't super urgent). Thanks chat-gpt, too 🤖

**Comment by NC-RVSO** [comment]
Perfect @nathanwoulfe  :) 
Keep me posted!

**Comment by nathanwoulfe** [comment]
@NC-RVSO turns out this is due to casing in the CMS' backoffice build, rather than Workflow-specific - in the navigation resource, we generate template URLs for tree items, and as part of that work we check for package tree folders (like those in Workflow). In the generated template URL we include the segement `/backoffice/` with a lower-case `b`, which was the cause of this issue, as Workflow builds its backoffice assets into an upper-case `Backoffice` folder.

I've updated the build to change casing so all references to the Workflow backoffice folder are lowercase, which should be fine UNLESS there are cases in the CMS codebase that expect uppercase Backoffice...

**Comment by NC-RVSO** [comment]
@nathanwoulfe Great to hear that you found the issue! :D I will close this issue after updating and testing everything works without my hack :)

**Comment by nathanwoulfe** [comment]
@NC-RVSO releases are on NuGet now, this issue should be resolved 👍

**Comment by NC-RVSO** [comment]
Tested and it works like a charm! :D
