### ISSUE TITLE
Editing content that's in a Workflow

### ISSUE THREAD

**Issue by kgunter1237** [umbraco/Umbraco.Workflow.Issues#18]
In version 10.1.1 and prior Administrators for a site could edit documents that are in workflows, but since version 10.1.2 this is no longer possible. Is this an intentional change, and if so would it be possible for there to be an option in the settings to allow Admins to edit documents that are in workflows? 

---
_This item has been added to our backlog AB#30333_

**Comment by nathanwoulfe** [comment]
Hey @kgunter1237 I don't believe this was intentional, and agree that making it configurable makes sense. Will pick this up for the next release

**Comment by nathanwoulfe** [comment]
New config option was released yesterday in the x.2.2 and 12.0.0 releases 🐰
