### ISSUE TITLE
Translations 

### ISSUE THREAD

**Issue by erikjanwestendorp** [umbraco/Umbraco.Workflow.Issues#23]
Just curious if there are any plans to translate Umbraco Workflow to other languages? We gave a demo to one of our clients and they were enthusiastic but want to use the features in Dutch. Of course I want to help with translations if this is desired 😄

**Comment by nathanwoulfe** [comment]
Hey @erikjanwestendorp, there are very limited translations for Danish, but so far that's all. The UI is all localizable (I won't say 100% but it's very close), so the blocker is only (!) finding willing translators. 

If you're happy to help with Dutch, that would be amazing. I'll check internally to see if there's any considerations I might not be considering, but can't that there would be any issues.

**Comment by erikjanwestendorp** [comment]
@nathanwoulfe Of course I'm happy to help, let me know if there is an issue and otherwise I will do the translation to dutch 😄

**Comment by nathanwoulfe** [comment]
@erikjanwestendorp I'll get back to you next week - we've previously offered some compensation/incentive for community folk contributing translations to commercial packages (it's not right for us to accept your voluntary work on a product we sell, doesn't seem fair). I'll talk to Andy when he's back from holidays, and we'll make sure your efforts are rewarded.

**Comment by erikjanwestendorp** [comment]
Thanks for your reply natan, this sounds really good to me! 😄 I'll look forward to your answer 👍

**Comment by nathanwoulfe** [comment]
Will be included in the next patch, thanks for your help @erikjanwestendorp

**Comment by nathanwoulfe** [comment]
Resolved in 10.2.3, 11.2.3 and 12.0.1 🚀
