### ISSUE TITLE
Add 'This feature requires a license.' message to Document-type reviews

### ISSUE THREAD

**Issue by erikjanwestendorp** [umbraco/Umbraco.Workflow.Issues#24]
In most places a message appear if a license is required except for  the Document-type reviews. This is not a big issue but for consistency also nice to add the message here?

![image](https://github.com/umbraco/Umbraco.Workflow.Issues/assets/7831614/c4e30f5d-a318-4d7b-9de0-f81800618b24)
Like: 

![image](https://github.com/umbraco/Umbraco.Workflow.Issues/assets/7831614/e6366c2a-280c-45c1-9910-71fda0c83580)

---
_This item has been added to our backlog AB#30603_

**Comment by nathanwoulfe** [comment]
Most definitely should have the message - no point in allowing setting a value when it's only going to be ignored. Will fix for the next patches and for v12 👍

**Comment by nathanwoulfe** [comment]
Released yesterday as part of x.2.2 and 12.0.0 versions 🍾
