### ISSUE TITLE
Tasks requiring my approval is empty on Content - Workflow when Exclude mode is on

### ISSUE THREAD

**Issue by AndriiDzendzia** [umbraco/Umbraco.Workflow.Issues#25]
`Tasks requiring my approval` is empty on Content - Workflow when Exclude mode is on

Reproduction
------------

### Bug summary

Approver see an empty state of Tasks requiring my approval
![image](https://github.com/umbraco/Umbraco.Workflow.Issues/assets/87599681/8cdd895f-80e2-4fb7-acce-f6fab022e881)
Admin the same
![image](https://github.com/umbraco/Umbraco.Workflow.Issues/assets/87599681/5a9bcaff-99d3-4528-9ce0-9271444b7296)
Active workflows contain a request from Editor
![image](https://github.com/umbraco/Umbraco.Workflow.Issues/assets/87599681/b3e1c6e6-cff1-4535-a43f-791cd2bebebe)
Approver user can approve this request
![image](https://github.com/umbraco/Umbraco.Workflow.Issues/assets/87599681/396105fd-2377-4419-b67d-90e69c4a128e)

### Specifics

Umbraco.Cms - 12.0.0-rc3
Umbraco.Workflow - 12.0.0-rc2

### Steps to reproduce

Preconditions: there are an Editor user and an Approver user, both are in the Approvers group. Exclude mode is on.

1. Editor requests page publishing
2. Nor editor neither approver can see the request on the Content - Workflow - Tasks requiring my approval

### Expected result
Approver can see the request on the Content - Workflow - Tasks requiring my approval

### Actual result

nor editor neither approver can see the request on the Content - Workflow - Tasks requiring my approval

**Comment by nathanwoulfe** [comment]
Thanks @AndriiDzendzia, that definitely smells buggy... I'll aim to fix for the next patches and v12.

**Comment by nathanwoulfe** [comment]
Fixed in the x.2.2 and 12.0.0 releases 🚀
