### ISSUE TITLE
Exclude from review by default

### ISSUE THREAD

**Issue by LeaTark** [umbraco/Umbraco.Workflow.Issues#28]
It might be helpful for Content Review to have the option to exclude by default then list only the individually configured items.
At the moment, the report fills up with every page in every language even when the default period is set to 0.

**Comment by nathanwoulfe** [comment]
Hey @LeaTark, I'll look into this - when default is 0, it should not be including any items, which then allows excluding all, and only opting in for the required nodes/types

**Comment by nathanwoulfe** [comment]
RC for the next release is on the way to Nuget, with a fix for this issue 🚀
