### ISSUE TITLE
When using a test license, unable to set New node approval flow and Document type approval flows in Workflow Settings

### ISSUE THREAD

**Issue by eshanrnh** [umbraco/Umbraco.Workflow.Issues#3]
When using a test license, unable to set New node approval flow and Document type approval flows in Workflow Settings

Reproduction
------------

If you're filing a bug, please describe how to reproduce it. Include as much
relevant information as possible, such as:

### Bug summary

When using a test license, unable to set New node approval flow and Document type approval flows in Workflow Settings

### Specifics

Using Umbraco CMS version 11.0.0-rc4, Workflow v11.0.0-rc2

### Steps to reproduce

1. Enable test license in appsettings.json
2. Run the app.
3. Go to Workflow Settings and click Add in New node approval flow and Document type approval flows.
4.  Doesn't load approval groups/Doesn't open a selectiopn pane.

### Actual result

https://user-images.githubusercontent.com/82437098/201876164-b96bc903-e2e4-49c1-85d9-f730df770e8d.mp4

**Comment by nathanwoulfe** [comment]
Pretty certain this is related to the other license-related issue #2 - all works fine after I've fixed the license type bug.
