### ISSUE TITLE
Content review inheritance

### ISSUE THREAD

**Issue by LeaTark** [umbraco/Umbraco.Workflow.Issues#32]
Would it be possible to make inheritance optional for individually reviewed content items?
We were looking for a reminder when a section of content should be reviewed and a one-click solution for the reviewer to mark it as reviewed.
As it is, they must either action each node separately or have 'treat publishing as a review' enabled then republish the tree.
Though that creates a path for content editors to bypass reviewers and messes with published dates.

**Comment by nathanwoulfe** [comment]
Hi @LeaTark, just so I'm on the right track - you're thinking of an option to mark descendants as reviewed when reviewing an individual node (but only descendants where review permissions are inherited)? Definitely want to avoid unnecessary publishing 😄

**Comment by LeaTark** [comment]
Yeah, something like that which would keep the current behavior when inherited (the default) but also allow for there to be no inheritance.
e.g. a setting when adding an individual node for review.

**Comment by nathanwoulfe** [comment]
Ah ok, so not quite what I thought - idea would be to make inheritance optional, not to allow reviewing descendants via inheritance (eg reviewing ancestor reviews descendants).

Will see what I can make work.

**Comment by nathanwoulfe** [comment]
RC for the next release is on the way to Nuget, with a fix for this issue 🚀 

This is fixed as a result of #28, so it's now possible to:
- enable content reviews
- set the default period to 0, effectively excluding everything
- opt in individual nodes via node config
- celebrate no longer having any reviews inherited
