### ISSUE TITLE
When overriding Email notification templates other mails won't trigger when no custom template is set

### ISSUE THREAD

**Issue by RunnicFusion** [umbraco/Umbraco.Workflow.Issues#36]
**Issue**: When setting a custom template path, al non existing notification templates won't trigger Workflow notifications
**Solution**: Send default notification e-mail when no override is set for notification OR maybe even when an error occured in custom template

Did I miss something or did I stumbled upon a bug?
Would love to hear ;)

**Versions**
Umbraco: 10.6.1
Umbraco Workflow: 10.2.2+2a26d9a

**Steps to reproduce issue:**
[IN CMS]
- Open 'Workflow' section
- Press 'Settings'
- Open 'Notifications' "content app"
- Edit, for example. 'Approval rejection' by pressing edit
- Copy default cshtml markup to clipboard

[In VisualStudio / IDE]
- open Appsettings.json file and add inside Umbraco object:
```
"Workflow": {
      "EmailTemplatePath": "~/Views/Partials/WorkflowEmails"
    }
```
- Create new file with clipboard content inside location `[projectpath]\Views\Partials\WorkflowEmails\ApprovalRequest.cshtml`
- don't any other template files for now
- restart application

[Workflow flow]
- Publish node for review
- Review mail is sent correctly (also using new custom template)
- Approve review
- No e-mail is set, even when 'Approved and completed' notification e-mail is set in CMS

[Logs]
- Open log file:
`Unable to find email template "EmbeddedResources/EmailTemplates/ApprovedAndCompleted.cshtml"`

**Screenshots**:
![image](https://github.com/umbraco/Umbraco.Workflow.Issues/assets/11329216/35b9d35b-a79e-4344-8b7d-213985caed6a)
![image](https://github.com/umbraco/Umbraco.Workflow.Issues/assets/11329216/c948934e-cbfc-4a90-81f4-0cb4ae9f4105)
![image](https://github.com/umbraco/Umbraco.Workflow.Issues/assets/11329216/349c72d5-d28b-4c64-b876-90c758009020)

**Comment by nathanwoulfe** [comment]
Hey @RunnicFusion, I've removed that configuration option in v12, guessing that issues like this one might be why... Does it work as expected if you don't modify the view location?

**Comment by nathanwoulfe** [comment]
Have tried the reproduction steps, but it seems to work fine for me - all emails are sent correctly. 

The `EmailTemplatePath` app setting isn't actually used, so it won't be the cause of your issues (property is obsoleted in v10, but isn't used anywhere). The path in your example is the same as the default path used internally, hence why your custom template is still used (try a different path, and you'll get the default template).

Annnd I've just had a Friday afternoon epiphany - given you're on 10, there's an additional setup step that I think is missing from the docs... In `Startup.cs`, the `ConfigureServices` method needs to look something like this:

```csharp
        public void ConfigureServices(IServiceCollection services) => services.AddUmbraco(_env, _config)
                .AddBackOffice()
                .AddWorkflowEmailTemplateProvider()
                .AddWebsite()
                .AddComposers()
                .Build();
```

This adds `.AddWorklowEmailTemplateProvider()`, which MUST come before `.AddWebsite()`.  This is specific to Umbraco 10, and is required as Umbraco wraps the default RazorViewEngine implementation, which happens before Workflow's composer runs, so without this addition the EmbeddedFileProvider was added after the DI container was frozen.

Let me know if this fixes the issue...

**Comment by RunnicFusion** [comment]
Thnak's for your update. Seems ok!
