### ISSUE TITLE
Trigger Workflow events when updating content trough contentService/API

### ISSUE THREAD

**Issue by RunnicFusion** [umbraco/Umbraco.Workflow.Issues#37]
Could you please add the functionality to trigger Umbraco Workflows the same way as inside the CMS for contentService requests?

For example:
When creating nodes by code no workflow triggers will run.

Current installed version of Umbraco Workflow: 10.2.2+2a26d9a

**Comment by nathanwoulfe** [comment]
This can be done now, using some custom code to initialise the workflow.

The below class can be registered on the DI container, then injected into the class where you're creating content, then finally called via `_approvalWorkflowIntiator.Initiate(content)`. Of course this could be done inline in your existing code, but I'd keep it separate for easy re-use and extension.

Given this is applying to a new node, it will use the inherited (or document type) permissions for the node. It's possible to set the permissions programmatically too. Node needs to be saved before submitting for approval as it must have an identity.

```csharp
public class ApprovalWorkflowInitiator : IApprovalWorkflowInitiator
{  
  private readonly IWorkflowProcessGenerator _workflowProcessGenerator;

  constructor(IWorkflowProcessGenerator workflowProcessGenerator) {
    _workflowProcessGenerator = workflowProcessGenerator;
  }

  public async Task Initiate(IContent content)
  {
    IWorkflowProcess process = _workflowProcessGenerator.GetProcess(WorkflowType.Publish);

    InitiateWorkflowRequestModel model = new()
    {
      NodeId = content.Id,
      ContentTypeId = content.ContentTypeId,
      Publish = true,
      UserId = Umbraco.Cms.Core.Constants.Security.SuperUserId,
      Comment = "New content for approval",
      VariantToInitiate = "*", // or an ISO code for a specific variant
    };

    await process.InitiateWorkflow(model);       
  }
}

```

**Comment by nathanwoulfe** [comment]
@RunnicFusion, tagging you in case you missed the notification.

**Comment by RunnicFusion** [comment]
hi @nathanwoulfe, thanks for your update! :)

**Comment by nathanwoulfe** [comment]
No worries, hopefully something useful. I do need to look at properly documenting the public API, which will make these sorts of extensions a lot clearer.
