### ISSUE TITLE
Notes are not being sent after the initial request for publish step - neither approval or Rejection 

### ISSUE THREAD

**Issue by gabador-mof** [umbraco/Umbraco.Workflow.Issues#39]
When I try to approve or reject a workflow item, I don't see where the message I have typed appears. 

<img width="549" alt="image" src="https://github.com/umbraco/Umbraco.Workflow.Issues/assets/64405523/3b8322f0-9164-4e3a-947e-12aba9efbe99">

If you add a comment here, and press reject or approve, it is not shown either in the email, or the workflow step, or the History, thus the editor is not notified why they have had their node rejected. Subsequent re-requests are also not notified, like I fixed x or y... 

### Steps to reproduce
Try and approve/reject a workflow item, or rejet, then re-submit. 

### Expected result
Comment is displayed somewhere
### Actual result
it is not

This is workflow 11.2.3
Umbraco Version 11.4.2

**Comment by nathanwoulfe** [comment]
Hi @gabador-mof do you not see something similar to the below, when viewing the active workflow (or history)?

![image](https://github.com/umbraco/Umbraco.Workflow.Issues/assets/3248070/f78b8566-1449-4730-8eab-4af89ca71456)

The workflow emails are intentionally minimal, as these can be modified to suit the requirements of your site. 

If you can provide more detail reproduction steps to highlight the issue, I'm happy to look into it further.

**Comment by nathanwoulfe** [comment]
Has the Approvals group been modified after the workflow process was initiated? The group has no members, but was able to reject the task, so I think it's either the UI not understanding what to do when the group is empty, or not being able to display the comment when it has no users associated with the task. 

Will have a look at reproducing, expect it will be related to the empty approvals group.

**Comment by gabador-mof** [comment]
The approval group is inheriting from an Umbraco User group. It has no explicit users in it...

**Comment by gabador-mof** [comment]
Hi Nathan, 

On the above, I have another question. Regarding these comments, the users want to get notified in the email what the rejection reason, or re-submit reason was. I cannot see where this is stored, as the model contains a CurrentStep.Instance property, but the comment in there is not the one I want to see. Let me know what I can use in the email template to include comment in the current step

**Comment by nathanwoulfe** [comment]
Hi @gabador-mof. You should be able to get the comment from `Model.CurrentTask?.Comment` - the email model will provide the task that triggered the email (which is nullable as the email may not always be related to a task action).

As for the inherit members, that's a bug, I'm looking into how to best resolve it.

**Comment by nathanwoulfe** [comment]
Hey @gabador-mof there's a patch release due today (September 26) for 10, 11 and 12 which resolves the issue with inherited memberships.

**Comment by gabador-mof** [comment]
Thanks Nathan!
