### ISSUE TITLE
Clicking on Edit approval group in New node approval Flow throws an error

### ISSUE THREAD

**Issue by eshanrnh** [umbraco/Umbraco.Workflow.Issues#4]
In the Workflow Settings section, when you click on Edit in New Node Approval Group, it throws an error

Reproduction
------------

If you're filing a bug, please describe how to reproduce it. Include as much
relevant information as possible, such as:

### Bug summary

In the Workflow Settings section, when you click on Edit in New Node Approval Group, it throws an error
![image](https://user-images.githubusercontent.com/82437098/201892521-abd6d3c8-46a1-4109-a533-cc38b9a895b7.png)

### Specifics

Using Umbraco CMS version 11.0.0-rc4, Workflow v11.0.0-rc2

### Steps to reproduce

1. Go to the Workflow Settings section.
2. Click on Edit in New node approval flow
3. Throws an error.

### Actual result

https://user-images.githubusercontent.com/82437098/201893033-251d6985-013c-4131-b5d7-6b958b13d91b.mp4

**Comment by nathanwoulfe** [comment]
Heya @eshanrnh this will be fixed in the next RC - related to #2
