### ISSUE TITLE
Swedish localization

### ISSUE THREAD

**Issue by pasindu1997** [umbraco/Umbraco.Workflow.Issues#44]
Hi Team,

My client is using Umbraco workflow to manage their contents but the client wants to use this in Swedish language. when I select the language as Swedish in Umbraco the workflow tab's content does not fully translate (some words get translated but not some). What is critical is the settings page doesn't loads and gives a 404 error. Can I know if Swedish localization is supported if not can we have a fallback language, because at the moment I am getting errors due to localization. It would be great if we can load the page in English as a fallback.

![image](https://github.com/umbraco/Umbraco.Workflow.Issues/assets/47180202/5fc80281-710a-43d7-946a-eb9d9187ca18)

**Comment by nathanwoulfe** [comment]
Hey @pasindu1997, this is reallllllly strange - there's a query deep in Workflow that may pass -1 as an argument. When the user is using the Swedish language, that -1 isn't the same as -1 in other languages. So it's less about the missing translations (which would be great to fix if we can find a Swedish speaker to translate for us), and more about an oddity in the culture. 

I'll dig into it tomorrow, and aim to include a fix in the next minor, which is available as an RC next week.

**Comment by nathanwoulfe** [comment]
It's an encoding issue, as far as I can tell. I have a dirty solution, waiting for feedback from colleagues for a proper fix.

**Comment by pasindu1997** [comment]
@nathanwoulfe, Really appreciate your quick reply. Unfortunately, I am not a Swedish speaker but my team has Swedish-speaking members I will let them know of this opportunity. 

Sounds good. It would be nice if we can have the Swedish translations but if it is not possible, a fallback to English would also be fine until the team has a solid solution.

let us know if there is a fix. I'll look forward to an update on this.

**Comment by nathanwoulfe** [comment]
Fix will be in the 10.3.0, 11.3.0 and 12.1.0 RC next week. With the bug squashed, the missing translations will all fall back to the English so while it's not ideal, the backoffice will function correctly. If there's anyone on your team interested in working on translations, please let me know so I can look into compensating them for their time.

**Comment by nathanwoulfe** [comment]
Fix is on the way to Nuget now, in the new RC 🚀
