### ISSUE TITLE
Number of pending items incorrect

### ISSUE THREAD

**Issue by gabador-mof** [umbraco/Umbraco.Workflow.Issues#45]
A brief description of the issue goes here.

When seeing the number of pending items in the Workflow Dashboard, it shows different numbers to what's actually pending approval

https://www.loom.com/share/39278c78355d4ce0b707156af1540ff3

### Specifics

This is on Umbraco 11.4.2  with Workflow 11.3.1
### Steps to reproduce

I went to Workflow app, then just on the dashboard I could see 7 pending items. Clicking on it showed 0 pending items. Also 0 pending items in the list below.

**Comment by nathanwoulfe** [comment]
Looks like some maths that doesn't quite add up... Thanks for letting us know.

**Comment by nathanwoulfe** [comment]
@gabador-mof this should be all good in the latest patch, which is on NuGet now.

Issue was due to the charting not correctly setting the dates in the data series, so items were erroneously included in the previous/next day.
