### ISSUE TITLE
Adding a content node in Document type reviews throws an error

### ISSUE THREAD

**Issue by eshanrnh** [umbraco/Umbraco.Workflow.Issues#5]
Adding a content node in Document type reviews throws an error

Reproduction
------------

If you're filing a bug, please describe how to reproduce it. Include as much
relevant information as possible, such as:

### Bug summary

In Content reviews, if you try to add the same content node again it throws an error 
![image](https://user-images.githubusercontent.com/82437098/202179335-cbee9909-55dc-4b78-98a3-84194f4ca691.png)

### Specifics

Umbraco version 11.0.0-rc4 and Umbraco Workflow: 11.0.0-rc2

### Steps to reproduce

1. Go to Content Reviews.
2. In Settings, enable content reviews.
3. Click Add in Content item reviews and select a content node.
4. In the Add content item review settings select a review group.
5. Click Submit.
6. Click Save Settings.
7. Click Add in Document Type Reviews and select a content node.
8.  In the Add Document Type review settings select a review group.
9. Click Submit.
10.  Click Save Settings

### Expected result

Shouldn't throw an error. Maybe I'm missing some setting/configuration but should either disable selecting the content nodes or show a pop-up as to what needs to be done.

### Actual result

https://user-images.githubusercontent.com/82437098/202184366-4078f701-d208-4457-8897-9c064fb7e038.mp4

**Comment by nathanwoulfe** [comment]
Couple of things fixed here:
- adds state to selected nodes to prevent selecting twice
- refactors SQL queries to ensure variants are handled correctly

Can now add node/doctype config, for both variant and invariant sites, with no more errors 👍 Will be in RC3
