### ISSUE TITLE
Split-view allows me to publish content even though lock active content is turned on

### ISSUE THREAD

**Issue by krebil** [umbraco/Umbraco.Workflow.Issues#53]
**A brief description of the issue goes here.**

When running workflows in a multilingual site setup using variants. Default "save and publish" button shows up in splitview.

This could be an issue if you have 3rd party editors that need approval before their content is published, for one it could be misused to bypass approval flows. But it's also kind of confusing for editors that primarily do translation work.

**Reproduction**

This happens on Umbraco v13.1.0 with workflow v13.0.2 running on the starter kit.

When I open split view the default "save and publish" button appears instead of the workflow specific buttons.

English version has an active workflow: 
![image](https://github.com/umbraco/Umbraco.Workflow.Issues/assets/1363512/a0d46a22-3035-4a29-960b-febea5742231)

Danish version should have a request publish button:
![image](https://github.com/umbraco/Umbraco.Workflow.Issues/assets/1363512/97e86a89-d3c1-46df-a171-ad91f3297191)

When opening the split-view the button is replaced with "save and publish"
![image](https://github.com/umbraco/Umbraco.Workflow.Issues/assets/1363512/eae1e00b-f108-46d3-b017-cfab750caaa6)

If i close the split-view the save and publish button persists.
Clicking the button allows me to publish the page even if `lock active content` is turned on.

![image](https://github.com/umbraco/Umbraco.Workflow.Issues/assets/1363512/020a9548-e1ca-4d42-b99b-35a036663737)

---
_This item has been added to our backlog AB#37666_

**Comment by nathanwoulfe** [comment]
Heya @krebil, thanks for letting us know - split screen has always been a bit of a pest since we're juggling concurrent editorScopes. Will let you know when this is progressing

**Comment by krebil** [comment]
@nathanwoulfe Sounds good, let me know if there is anything I can do to help

**Comment by nathanwoulfe** [comment]
@krebil this is fixed in the latest patch releases - 10.3.7, 12.2.4 and 13.0.3. Introduces a new UI/UX for the submit-workflow process, screenshots in #52, documentation to be published shortly.

**Comment by krebil** [comment]
Thanks @nathanwoulfe
