### ISSUE TITLE
Unpublish request comes through as publish

### ISSUE THREAD

**Issue by gabador-mof** [umbraco/Umbraco.Workflow.Issues#55]
A brief description of the issue goes here.

<img width="816" alt="image" src="https://github.com/umbraco/Umbraco.Workflow.Issues/assets/64405523/d802448e-0594-40fa-a204-9e208e0fd9d8">

<img width="1595" alt="image" src="https://github.com/umbraco/Umbraco.Workflow.Issues/assets/64405523/f3d7742a-43bd-469e-83f0-4080a226e83e">

When requesting an unpublish the approver is not told that this is happening. It just comes through as a publish request with a comment. 

Reproduction
------------

If you're filing a bug, please describe how to reproduce it. Include as much
relevant information as possible, such as:

### Bug summary

When requesting an unpublish the approver is not told that this is happening. It just comes through as a publish request with a comment. 

### Specifics
version 11.4.2 U
W:  v11.3.2

### Steps to reproduce

Send an item in workflow for unpublishing in the future... 

### Expected result

Get a comment/history item that says an unpublish is requested

### Actual result
 
Just publish in message

**Comment by nathanwoulfe** [comment]
Hey @gabador-mof, unfortunately this issue relates to an EOL version (the version 11 releases of Umbraco and Workflow are no longer supported as of December 1 2023) so won't be fixed. Best bet is to update to 13, which is supported until December next year.
