### ISSUE TITLE
Unable to hide Workflow Section, Dashboard, and ContentApp from backoffice

### ISSUE THREAD

**Issue by kikodev714** [umbraco/Umbraco.Workflow.Issues#56]
**Description**
Unable to hide Workflow Section, Dashboard, and ContentApp from backoffice

**Details**
We are trying to explore the capabilities of Umbraco Workflow (10.3.6) to see if we want to purchase it. One avenue that we're trying to explore is the ability to hide and show the Workflow Section, Dashboard and Content Apps from the Backoffice so that we can enable it to some clients and disable it to some.

We're looking add hiding them using a Composer so that we can add some more business logic around it. Something like:
builder.Sections().Remove<>();
and
builder.Dashboards().Remove<>();

I tried to remove the dashboard by doing this:

builder.Dashboards().Remove(WorkflowAdminDashboard)();

But it's giving me error saying I don't have access to WorkflowAdminDashboard

Am I missing something?

### Bug summary

Unable to hide Workflow Section, Dashboard, and ContentApp from backoffice

### Specifics

Using **Umbraco 10.6.1** + **Umbraco Workflow 10.3.6**

### Steps to reproduce

Attempt to hide the Workflow Section and Dashboard by adding this in a composer:

            builder.Sections().Remove<WorkflowSection>();
            builder.Dashboards().Remove(WorkflowAdminDashboard)();

It won't work with error message: "WorkflowSection" is inaccessible due to its protection level

### Expected result

I should be able to hide the Workflow Section, Dashboard and Content up dynamically.

**Comment by nathanwoulfe** [comment]
Hi @kikodev714 

Not missing anything - for some reason the dashboard, content app and section definitions are all internal classes. Those can be made public in the next patch, which should solve your problems.

However... I'm not sure that's the best approach. Is there a reason why you wouldn't just not install Workflow into projects where it isn't being used? Installing will still create tables, schedule tasks, install client assets etc. I'm not 100% certain what will happen if those client assets exist but the related app/section does not exist. In most cases the JS relies on elements in the DOM, but there are some where the javascript executes independently of the DOM.

**Comment by kikodev714** [comment]
@nathanwoulfe  Thank you for the response. What you explained does make sense.

To explain a bit, we have a base code that serves as a template for all of our project installs. We would like to have the Workflow package installed in this base code so that we can just deploy them easily on all our project installs. The problem is hiding the Workflow to project installs that don't need them.

**Comment by nathanwoulfe** [comment]
Cool cool, that make sense, so long as you're happy with carrying some additional tables and tasks. Realistically, not a big issue, just wanted to make sure you're aware.

I'll sort those classes in the next patch, and all should be ok.

**Comment by kikodev714** [comment]
@nathanwoulfe Thank you for this. 

At first we thought we can use the user group service to hide but it can only hide the section area:

`sampleGroup.AddAllowedSection("workflow");`

The Workflow dashboard and content app still appears.

It'll be nice if we can hide everything based on user group permissions too.

**Comment by nathanwoulfe** [comment]
@kikodev714 just FYI - making those classes public fixes this one. Intending to release a patch early next week for 10, 12 and 13.

**Comment by kikodev714** [comment]
@nathanwoulfe Great!. Thanks for this. 
Follow-up question. Would this also handle the ContentApp or just Dashboard and Section?

**Comment by nathanwoulfe** [comment]
I'll confirm before I release, but it certainly should.

**Comment by kikodev714** [comment]
@nathanwoulfe Thank you. You've been very helpful.

**Comment by nathanwoulfe** [comment]
Hey @kikodev714 patches are available now

**Comment by fbpenalosa** [comment]
@nathanwoulfe  Thank you for your update!

**Comment by kikodev714** [comment]
@nathanwoulfe  Thank you for your update. Does it include hiding content apps? How do we do that?

**Comment by nathanwoulfe** [comment]
It does indeed include content apps, which can be hidden like so:
`builder.ContentApps().Remove<WorkflowContentApp>();`

**Comment by nathanwoulfe** [comment]
Seems markdown via email isn't supported, but you get the idea.
