### ISSUE TITLE
Error sending content review reminder emails

### ISSUE THREAD

**Issue by jplatfordquba** [umbraco/Umbraco.Workflow.Issues#57]
We are trying to setup the package on an Umbraco Cloud installation, and all seems well except for the content review reminder emails. Which we are not receiving. I have noticed that error messages can be seen in the event log - this seems to appear a few times in the log (so looks like it is re-attempted). All other emails, that we have tested, appear to be working fine.

There are a few pages setup for content review e.g.:
![image](https://github.com/umbraco/Umbraco.Workflow.Issues/assets/121883703/d10d65a2-b5b1-4f10-bda2-abe5bd35223e)
Content review settings:
Content reviews are enabled
Send notifications enabled
Review period set to 0
Reminder threshold set to 1 day

The error:
![image](https://github.com/umbraco/Umbraco.Workflow.Issues/assets/121883703/403ecaaa-8e7c-42b2-9d91-546fa870d3e5)

Umbraco Cloud: v13.1.0
Umbraco Worfklow: 13.0.5

**Comment by nathanwoulfe** [comment]
Hey @jplatfordquba, looks to me like it's related to accessing UmbracoContext in a hosted service, which won't have a web context. Interesting though that you're the first to report it given that feature has existed for quite a while, and there's a similar email generator for workflow task emails which I'd expect to fail under the same circumstances.

Will have a look into it.

**Comment by QubaDigitalUK** [comment]
Hi,

Sorry to chase but is there any update on this?

Thanks

**Comment by nathanwoulfe** [comment]
Hi @QubaDigitalUK, will aim to pick this up next sprint - priority is getting v14 releases ready, but will need to resolve this for all versions too

**Comment by nathanwoulfe** [comment]
@QubaDigitalUK @jplatfordquba I have a fix for this, will have a patch out next week for 10, 12 and 13.

**Comment by nathanwoulfe** [comment]
Heya @QubaDigitalUK @jplatfordquba the patches fixing this issue are available now 👍
