### ISSUE TITLE
Content review list

### ISSUE THREAD

**Issue by benwoodTPT** [umbraco/Umbraco.Workflow.Issues#59]
A brief description of the issue goes here.

There's a list of pages at the bottom of this Stale content list that I can't navigate through. It suggests there's 10+ pages but the navigation e.g. 'Next' page doesn't respond when clicked so I can't see the other pages

![image](https://github.com/user-attachments/assets/411809bc-23ba-4017-95a3-60616fe8064b)

Reproduction
------------

If you're filing a bug, please describe how to reproduce it. Include as much
relevant information as possible, such as:

### Actual result

---
_This item has been added to our backlog AB#42376_

**Comment by nathanwoulfe** [comment]
Hey @benwoodTPT can you please confirm the Umbraco + Workflow versions

**Comment by benwoodTPT** [comment]
Yes sure @nathanwoulfe it's CMS version 13.1.0 and Workflow version 13.0.7

**Comment by nathanwoulfe** [comment]
Hey @benwoodTPT this is fixed in 13.1.0, which is available now. This version bumps the minimum Umbraco dependencies to 13.1, which won't be a problem for you, but worth mentioning for anyone else who might be reading this comment 😄
