### ISSUE TITLE
Pop-up notification contains (*)

### ISSUE THREAD

**Issue by eshanrnh** [umbraco/Umbraco.Workflow.Issues#61]
When you click on Request approval, the notification message contains (*) at the end.

Reproduction
------------

1. Go to a Document type.
2. Click Request approval.
3. Fill details and click Request publish.
4. A popup message appears stating: Workflow publish approval requested (*)

![image](https://github.com/user-attachments/assets/cdc50d57-3a86-4c68-9d4c-ef85dbf5e8ba)

**Versions;**

CMS: 14.1.1 and Workflow: 14.0.1

---
_This item has been added to our backlog AB#42590_

**Comment by nathanwoulfe** [comment]
Hey @eshanrnh, I need to update the message - the () value should be the variant submitted for approval, or in this case, it shouldn't be there at all, as it's an invariant workflow, so doesn't need the additional info.

**Comment by nathanwoulfe** [comment]
14.0.2 is available now 🚀
