### ISSUE TITLE
Save and Publish button is not displayed

### ISSUE THREAD

**Issue by eshanrnh** [umbraco/Umbraco.Workflow.Issues#62]
When I enable Extend Permissions in Settings, I do not see the Save and Publish button. I can only see the Request approval button irrespective of Extend Permissions being set to true or false.

**Versions;**

CMS: 14.1.1 and Workflow: 14.0.1

Reproduction
------------

1. Go to Workflow section.
2. In Settings, enable Extend Permissions.
3. Click Save.
4. Go to a Document Type.
5. The Request approval button is not replaced/extended with Save and Publish button

![image](https://github.com/user-attachments/assets/91a21cda-0d68-42e9-92d6-6552a7ed9fb3)
![image](https://github.com/user-attachments/assets/d884b522-d176-475b-84d8-15e11fe6c4ef)

---
_This item has been added to our backlog AB#42597_

**Comment by nathanwoulfe** [comment]
14.0.2 is available now 🚀
