### ISSUE TITLE
Document does not show locked notification/banner when lock is enabled.

### ISSUE THREAD

**Issue by eshanrnh** [umbraco/Umbraco.Workflow.Issues#63]
After enabling lock active content, the content is not locked or does not display any banner/notification while in a workflow.

**Versions;**

CMS: 14.1.1 and Workflow: 14.0.1

Reproduction
------------
1. Go to Workflow section.
2. In Settings, enable Lock active content.
3. Go to a doc type which is in workflow.
4. No message or notification is displayed notifying users that the content is locked for edits.

![image](https://github.com/user-attachments/assets/142bc31b-fe87-419e-ab42-c2757fead201)

---
_This item has been added to our backlog AB#42596_

**Comment by nathanwoulfe** [comment]
Hey @eshanrnh I've had a dig into this one, and a chat with the front-end team - they're adding a readonly mode for the document workspace, which is what I need to be able to make this work (the solution I used in earlier versions won't work in v14/web components).

I'll keep this open for anyone else who might come to raise the same/similar issue, and will update when I know what's happening at the CMS end.

**Comment by nathanwoulfe** [comment]
@eshanrnh took a little while, but this landed in Workflow 14.1 earlier this week 🚀 It's not perfect, but there are further changes coming in the CMS to better highlight when a document is readonly. When that is done, Workflow will benefit too.
