### ISSUE TITLE
WORKFLOW_PENDINGAPPROVAL label is displayed in the Pending Publish workflow overlay

### ISSUE THREAD

**Issue by eshanrnh** [umbraco/Umbraco.Workflow.Issues#64]
WORKFLOW_PENDINGAPPROVAL label displayed in the Pending Publish workflow overlay

Reproduction
------------

1. Go to doc type.
2. Click Request approval
3. Fill in details and click Request Publish.
4. Click Workflow Detail.
5. The Pending publish workflow overlay displays WORKFLOW_PENDINGAPPROVAL label instead of PENDING APPROVAL label.

![image](https://github.com/user-attachments/assets/18b419e1-09aa-4cfe-b1f1-3670937f71a9)

---
_This item has been added to our backlog AB#42592_

**Comment by nathanwoulfe** [comment]
14.0.2 is available now 🚀
