### ISSUE TITLE
When rejecting a task, Previous approval group is not displayed

### ISSUE THREAD

**Issue by eshanrnh** [umbraco/Umbraco.Workflow.Issues#65]
When rejecting a task, Previous approval group is not displayed

Reproduction
------------

1. Go to a doc type in workflow.
2. Click Workflow Detail.
3. Add comment and click Reject.
4. The Assign rejected task overlay does not display the Previous approval group.

![image](https://github.com/user-attachments/assets/25913273-8318-43cb-93ff-d94bbe3776c1)

---
_This item has been added to our backlog AB#42595_

**Comment by nathanwoulfe** [comment]
14.0.2 is available now 🚀
