### ISSUE TITLE
For invariant workflows, the comment column displays: <Comment> [FailedPublishMandatoryCultureMissing]

### ISSUE THREAD

**Issue by eshanrnh** [umbraco/Umbraco.Workflow.Issues#66]
In the History section, for invariant workflows, the comment column displays: good [FailedPublishMandatoryCultureMissing]

**Versions;**

CMS: 14.1.1 and Workflow: 14.0.1

Reproduction
------------
1. Create a document type with language variants.
2. Create workflows for this doc type.
3. Go to Worfklow -> History.

![image](https://github.com/user-attachments/assets/605c91ac-cdc3-4127-9696-e4af516fda9e)

---
_This item has been added to our backlog AB#42593_

**Comment by nathanwoulfe** [comment]
14.0.2 is available now 🚀
