### ISSUE TITLE
The clear button in the Filter overlay does not clear the records

### ISSUE THREAD

**Issue by eshanrnh** [umbraco/Umbraco.Workflow.Issues#67]
The clear button in the Filter picker overlay does not clear the records.

**Versions;**

CMS: 14.1.1 and Workflow: 14.0.1

Reproduction
------------

1. Go to Filters.
2. Add some filter.
3. Click Clear.

![image](https://github.com/user-attachments/assets/d865df6d-247e-43a9-bca4-8233deace884)

---
_This item has been added to our backlog AB#42594_

**Comment by nathanwoulfe** [comment]
14.0.2 is available now 🚀
