### ISSUE TITLE
The detail button displays Errored for approved invariant workflow

### ISSUE THREAD

**Issue by eshanrnh** [umbraco/Umbraco.Workflow.Issues#68]
The detail button displays Errored status for approved invariant workflow

**Versions;**

CMS: 14.1.1 and Workflow: 14.0.1

Reproduction
------------

1. Create doc type with language variants.
2. Create a workflow and approve it.
3. Go to Workflow -> History.
4. Click Detail on a record.
5.  The Workflow status shows Errored even though the workflow has been approved.

![image](https://github.com/user-attachments/assets/f1501ce9-c2a5-424a-ae07-5743e78323d1)

---
_This item has been added to our backlog AB#42591_

**Comment by nathanwoulfe** [comment]
Hey @eshanrnh I can't reproduce this one - are you able to share more detail re your configuration/settings?

I've tried with two languages, variant and invariant workflows, and nodes with two languages but only one variant created.

**Comment by nathanwoulfe** [comment]
I think I know what's happening here - I can reproduce this when the variant is not the default language, and the default language has not been published. 

This will be the same case for #66

**Comment by nathanwoulfe** [comment]
14.0.2 is available now 🚀
