### ISSUE TITLE
Active Workflows in Workflow section is blank

### ISSUE THREAD

**Issue by eshanrnh** [umbraco/Umbraco.Workflow.Issues#69]
Active Workflows in Workflow section is blank

**Versions;**

CMS: 14.1.1 and Workflow: 14.0.1

Reproduction
------------
1. Ensure a doc type is in workflow.
2. Go to Workflow -> Active workflows.

![image](https://github.com/user-attachments/assets/ed6407b1-18ce-4cfa-b0f8-7172316befee)

---
_This item has been added to our backlog AB#42599_

**Comment by nathanwoulfe** [comment]
Hey @eshanrnh  I suspect this was related to #66. I can't reproduce this one after resolving 66.
