### ISSUE TITLE
Filter Overlay throws an error

### ISSUE THREAD

**Issue by eshanrnh** [umbraco/Umbraco.Workflow.Issues#7]
When you click on Filter, it throws an error.

Reproduction
------------

If you're filing a bug, please describe how to reproduce it. Include as much
relevant information as possible, such as:

### Bug summary

1. Go to Workflow section.
2. Go to Active Workflows.
3. Click Filter. It throws an error.

### Steps to reproduce

1. Go to Workflow section.
2. Go to Active Workflows.
3. Click Filter. It throws an error.

### Expected result

Should open the filter pane.

### Actual result

![image](https://user-images.githubusercontent.com/82437098/203035513-828b0338-1bfa-4914-b647-743af7a8e144.png)

**Comment by nathanwoulfe** [comment]
@eshanrnh all sorted here too - fixed in rc3
