### ISSUE TITLE
Enable Offline Approval is not displayed when creating an Approval Group

### ISSUE THREAD

**Issue by eshanrnh** [umbraco/Umbraco.Workflow.Issues#70]
Enable Offline Approval is not displayed when creating an Approval Group. Is this feature removed or moved somewhere else?

**Versions;**

CMS: 14.1.1 and Workflow: 14.0.1

Reproduction
------------
1. Go to Workflow -> Approval Groups
2. Click Create.
3. Enable offline approval field is not available.

![image](https://github.com/user-attachments/assets/23496dcd-800f-46d3-a3cb-1c7c28fc10a6)

**Comment by nathanwoulfe** [comment]
Heya @eshanrnh offline approval isn't working yet (and may never on 14), so it's gone from the UI for now (or forever).

I'll keep this open for anyone else who might be looking for the feature, and will update when I know more.

**Comment by eshanrnh** [comment]
Sounds good, @nathanwoulfe 💪
