### ISSUE TITLE
Document type review settings overlay displays incorrect label

### ISSUE THREAD

**Issue by eshanrnh** [umbraco/Umbraco.Workflow.Issues#71]
When adding Document-type reviews in Content reviews, the overlay displays Add Content item review settings instead of **Add Document type review settings**

**Versions:**

CMS: 14.1.1 and Workflow: 14.0.1

Reproduction
------------
1. Go to Workflow section.
2. Go to Content reviews -> Settings.
3. Click **Add** in **Document-type reviews**.
4. Select Document Type.
5. Click Choose.
6. The overlay displays incorrect label

![image](https://github.com/user-attachments/assets/676879d7-53f8-4984-a37f-ddb0a9622afa)

---
_This item has been added to our backlog AB#42600_

**Comment by nathanwoulfe** [comment]
14.0.2 is available now 🚀
