### ISSUE TITLE
Status column is not displayed in the History table

### ISSUE THREAD

**Issue by eshanrnh** [umbraco/Umbraco.Workflow.Issues#72]
In the previous versions, the status column was displayed after the Comment column. In v14, the status column is missing. Is this removed for v14?

**Versions:**

CMS: 14.1.1 and Workflow: 14.0.1

Reproduction
------------

If you're filing a bug, please describe how to reproduce it. Include as much
relevant information as possible, such as:

### Actual result

---
_This item has been added to our backlog AB#42598_

**Comment by nathanwoulfe** [comment]
14.0.2 is available now 🚀
