### ISSUE TITLE
Add status button in filter picker overlay does not work.

### ISSUE THREAD

**Issue by eshanrnh** [umbraco/Umbraco.Workflow.Issues#74]
Clicking on Add status does not open an overlay to choose different statuses

![image](https://github.com/user-attachments/assets/c212d1a4-a0dc-41d9-b6d3-3544e38f931a)

Reproduction
------------

1. Go to Workflow -> History.
2. Click Detail
3. Click Filters.
4. Click Add status in the Filter picker.

---
_This item has been added to our backlog AB#42669_

**Comment by nathanwoulfe** [comment]
14.0.2 is available now 🚀
