### ISSUE TITLE
When adding a condition the approval groups are not populated in the drop-down list

### ISSUE THREAD

**Issue by eshanrnh** [umbraco/Umbraco.Workflow.Issues#76]
When adding a condition the approval groups are not populated in the drop-down list.

![image](https://github.com/user-attachments/assets/53eae2bc-5ae8-420b-8abc-6d9e6615573d)

Reproduction
------------
1. Go to Workflow -> Settings.
2. Click Add Document Type in Document Type approval flows section.
3. Select Document Type from the drop-down list.
4. Choose Approval Groups.
5. Click Add Condition.

---
_This item has been added to our backlog AB#42673_

**Comment by nathanwoulfe** [comment]
14.0.2 is available now 🚀
