### ISSUE TITLE
The Scheduling section on the Workflow history is empty

### ISSUE THREAD

**Issue by sniffdk** [umbraco/Umbraco.Workflow.Issues#82]
When reviewing the workflow history, the Scheduling section is always empty, even though the page was published on a scheduled date.

![image](https://github.com/user-attachments/assets/838d49e7-cbf1-46a0-95c7-aadb4aef2164)

Seen on Umbraco 13.4.1 and Workflow 13.2.0+faab5a3

### Expected result

I would expect to see information about when the scheduled date chosen for the workflow item in question

### Actual result

The section is just empty

---
_This item has been added to our backlog AB#44407_

**Comment by nathanwoulfe** [comment]
That should not be, smells like a mapping bug where the scheduling detail isn't populated, so we get an empty, useless box.

**Comment by nathanwoulfe** [comment]
Patches out now, this one should be working correctly now 🚀
