### ISSUE TITLE
Page is published through workflow, but workflow is not completed

### ISSUE THREAD

**Issue by bruceanewton** [umbraco/Umbraco.Workflow.Issues#85]
We are still in the process of converting our Umbraco V8 site to V13, and have come across an issue with workflows whereby we are able to 'Request publish' for a page, 'Approve' the publish request, which publishes the page, but does not complete the workflow (it still shows as 'Pending approval' in the page workflow history), which leads to issues when attempting to make further changes to the page at a later date.

Reproduction
------------

### Specifics

Umbraco version: 13.5.1
Umbraco.Workflow version: 13.2.1
Chrome browser version 122.0.6261.129, site running under IIS on Windows 10 (although the same issues occur when running directly from the Visual Studio IDE)

### Steps to reproduce

I'll detail the steps taken to reproduce the issue below.  

Note that I've spent hours trying to reproduce this issue on a vanilla Umbraco 13 site, but without success.  Hence, I'm wondering whether it's similar to the error that I reported and you resolved a while ago https://github.com/umbraco/Umbraco.Workflow.Issues/issues/79, which I also couldn't reproduce on a small site.  

It seems similar to that issue, because **if I turn off the workflow 'Send notifications' setting, then this issue appears to go away**.

Steps:

* Edit content on an existing page, which has only a Stage 1 workflow active, inherited from the parent (although I don't think that's important, but that's the setup of my test page).  
* Save the content (I've noticed that if you don't save the content before using the Request publish button, then the content isn't automatically saved, and there is no prompt to make you do so, which can lead to problems when completing the Publish request)
* Use Request publish to show to request publish panel
* Enter a change comment and use Request publish again to initiate the workflow for the page

![image](https://github.com/user-attachments/assets/8c7a6e85-1d51-40c1-9f31-c703c215f40e)

![image](https://github.com/user-attachments/assets/f48dec2c-d455-4b7c-8e48-b8dd3e9be675)

* Go to the Workflow section of the content page (as the current user who has administrative publishing permissions for the site), enter  an approval comment, and use Approve to approve the change and publish the page

![image](https://github.com/user-attachments/assets/29f8b99b-ba84-4936-aa34-ee25f4940cc3)

![image](https://github.com/user-attachments/assets/d985b5af-6c8a-415e-a112-afac463eb80a)

* Go back to the workflow section, and review the workflow History

![image](https://github.com/user-attachments/assets/b1ec85db-5699-4751-8955-69832c88f007)

At the point of the page approval, a number of messages are raised in the Umbraco trace log:

[
{"@t":"2024-10-17T05:00:19.5441194Z","@mt":"Workflow completed for node {Id}, page has been {Action}","@tr":"786f13d8abee21f54dbcae439a074e78","@sp":"9dc4005199b28b0b","Id":103161,"Action":"published","SourceContext":"Umbraco.Workflow.Core.Processes.WorkflowInstanceCompletionManager","ActionId":"555fd5ad-88ec-4174-8bb7-44f9b1e93b7e","ActionName":"Umbraco.Workflow.Web.Controllers.ActionsController.Approve (Umbraco.Workflow.Web)","RequestId":"800000e8-0009-ec00-b63f-84710c7967bb","RequestPath":"/umbraco/backoffice/workflow/actions/approve","ProcessId":89792,"ProcessName":"w3wp","ThreadId":83,"ApplicationId":"6b5d00dc72ce5284e0f562842f9308a3cff85b97","MachineName":"65CP373","Log4NetLevel":"INFO ","HttpRequestId":"6b4c7748-2845-47b1-a368-6cdeb0d5107d","HttpRequestNumber":29,"HttpSessionId":"120037cf-6064-c2f5-c04a-3977ca25ad7e"},
{"@t":"2024-10-17T05:00:19.5449862Z","@mt":"Exception ({InstanceId}).","@l":"Error","@x":"System.InvalidOperationException: There is already an open DataReader associated with this Connection which must be closed first.\r\n   at Microsoft.Data.SqlClient.SqlCommand.ValidateCommand(Boolean isAsync, String method)\r\n   at Microsoft.Data.SqlClient.SqlCommand.ExecuteNonQuery()\r\n   at Umbraco.Cms.Infrastructure.Persistence.FaultHandling.RetryPolicy.ExecuteAction[TResult](Func`1 func)\r\n   at System.Data.Common.DbCommand.ExecuteNonQueryAsync(CancellationToken cancellationToken)\r\n--- End of stack trace from previous location ---\r\n   at NPoco.Database.ExecutionHookAsync[T](Func`1 action)\r\n   at NPoco.Database.ExecuteNonQueryHelperAsync(DbCommand cmd)\r\n   at NPoco.Database.ExecuteAsync(Sql Sql)","@tr":"786f13d8abee21f54dbcae439a074e78","@sp":"9dc4005199b28b0b","InstanceId":"f31a0ba1","SourceContext":"Umbraco.Cms.Infrastructure.Persistence.UmbracoDatabase","ActionId":"555fd5ad-88ec-4174-8bb7-44f9b1e93b7e","ActionName":"Umbraco.Workflow.Web.Controllers.ActionsController.Approve (Umbraco.Workflow.Web)","RequestId":"800000e8-0009-ec00-b63f-84710c7967bb","RequestPath":"/umbraco/backoffice/workflow/actions/approve","ProcessId":89792,"ProcessName":"w3wp","ThreadId":83,"ApplicationId":"6b5d00dc72ce5284e0f562842f9308a3cff85b97","MachineName":"65CP373","Log4NetLevel":"ERROR","HttpRequestId":"6b4c7748-2845-47b1-a368-6cdeb0d5107d","HttpRequestNumber":29,"HttpSessionId":"120037cf-6064-c2f5-c04a-3977ca25ad7e"},
{"@t":"2024-10-17T05:00:19.5534201Z","@mt":"Exception ({InstanceId}).","@l":"Error","@x":"System.InvalidOperationException: There is already an open DataReader associated with this Connection which must be closed first.\r\n   at Microsoft.Data.SqlClient.SqlCommand.ValidateCommand(Boolean isAsync, String method)\r\n   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry, String method)\r\n   at Microsoft.Data.SqlClient.SqlCommand.ExecuteScalar()\r\n   at Umbraco.Cms.Infrastructure.Persistence.FaultHandling.RetryPolicy.ExecuteAction[TResult](Func`1 func)\r\n   at NPoco.Database.ExecuteScalarHelper(DbCommand cmd)\r\n   at NPoco.Database.InsertAsyncImp[T](PocoData pocoData, String tableName, String primaryKeyName, Boolean autoIncrement, T poco, Boolean sync)","@tr":"786f13d8abee21f54dbcae439a074e78","@sp":"9dc4005199b28b0b","InstanceId":"f31a0ba1","SourceContext":"Umbraco.Cms.Infrastructure.Persistence.UmbracoDatabase","RequestId":"800000e8-0009-ec00-b63f-84710c7967bb","RequestPath":"/umbraco/backoffice/workflow/actions/approve","ProcessId":89792,"ProcessName":"w3wp","ThreadId":83,"ApplicationId":"6b5d00dc72ce5284e0f562842f9308a3cff85b97","MachineName":"65CP373","Log4NetLevel":"ERROR","HttpRequestId":"6b4c7748-2845-47b1-a368-6cdeb0d5107d","HttpRequestNumber":29,"HttpSessionId":"0"},
{"@t":"2024-10-17T05:00:19.5583878Z","@mt":"An unhandled exception has occurred while executing the request.","@l":"Error","@x":"System.InvalidOperationException: There is already an open DataReader associated with this Connection which must be closed first.\r\n   at Microsoft.Data.SqlClient.SqlCommand.ValidateCommand(Boolean isAsync, String method)\r\n   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry, String method)\r\n   at Microsoft.Data.SqlClient.SqlCommand.ExecuteScalar()\r\n   at Umbraco.Cms.Infrastructure.Persistence.FaultHandling.RetryPolicy.ExecuteAction[TResult](Func`1 func)\r\n   at NPoco.Database.ExecuteScalarHelper(DbCommand cmd)\r\n   at NPoco.Database.InsertAsyncImp[T](PocoData pocoData, String tableName, String primaryKeyName, Boolean autoIncrement, T poco, Boolean sync)\r\n   at NPoco.Database.Insert[T](String tableName, String primaryKeyName, Boolean autoIncrement, T poco)\r\n   at NPoco.Database.Insert[T](T poco)\r\n   at Umbraco.Cms.Infrastructure.Persistence.Repositories.Implement.CacheInstructionRepository.Add(CacheInstruction cacheInstruction)\r\n   at Umbraco.Cms.Infrastructure.Services.CacheInstructionService.DeliverInstructionsInBatches(IEnumerable`1 instructions, String localIdentity)\r\n   at Umbraco.Cms.Infrastructure.Sync.BatchedDatabaseServerMessenger.SendMessages()\r\n   at Umbraco.Cms.Core.Events.INotificationHandler`1.Handle(IEnumerable`1 notifications)\r\n   at Umbraco.Cms.Core.Events.EventAggregator.PublishCore[TNotification](IEnumerable`1 allHandlers, IEnumerable`1 notifications)\r\n   at Umbraco.Cms.Core.Events.NotificationHandlerWrapperImpl`1.Handle[TNotification,TNotificationHandler](IEnumerable`1 notifications, ServiceFactory serviceFactory, Action`2 publish)\r\n   at Umbraco.Cms.Core.Events.EventAggregator.PublishNotifications[TNotification,TNotificationHandler](IEnumerable`1 notifications)\r\n   at Umbraco.Cms.Core.Events.EventAggregator.PublishAsync[TNotification,TNotificationHandler](IEnumerable`1 notifications, CancellationToken cancellationToken)\r\n   at Umbraco.Cms.Core.Events.EventAggregator.PublishAsync[TNotification](TNotification notification, CancellationToken cancellationToken)\r\n   at Umbraco.Cms.Web.Common.Middleware.UmbracoRequestMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)\r\n   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.InterfaceMiddlewareBinder.<>c__DisplayClass2_0.<<CreateMiddleware>b__0>d.MoveNext()\r\n--- End of stack trace from previous location ---\r\n   at Umbraco.Cms.Web.Common.Middleware.PreviewAuthenticationMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)\r\n   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.InterfaceMiddlewareBinder.<>c__DisplayClass2_0.<<CreateMiddleware>b__0>d.MoveNext()\r\n--- End of stack trace from previous location ---\r\n   at Umbraco.Cms.Web.Common.Middleware.UmbracoRequestLoggingMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)\r\n   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.InterfaceMiddlewareBinder.<>c__DisplayClass2_0.<<CreateMiddleware>b__0>d.MoveNext()\r\n--- End of stack trace from previous location ---\r\n   at SixLabors.ImageSharp.Web.Middleware.ImageSharpMiddleware.Invoke(HttpContext httpContext, Boolean retry)\r\n   at Umbraco.Forms.Web.HttpModules.ProtectFormUploadRequestsMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)\r\n   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.InterfaceMiddlewareBinder.<>c__DisplayClass2_0.<<CreateMiddleware>b__0>d.MoveNext()\r\n--- End of stack trace from previous location ---\r\n   at Usc.Infrastructure.BackOfficeProtectorMiddleware.Invoke(HttpContext context) in D:\\Git\\CorporateWebsiteV13\\Usc.Infrastructure\\BackOfficeProtectorMiddleware.cs:line 37\r\n   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)","@tr":"786f13d8abee21f54dbcae439a074e78","@sp":"9dc4005199b28b0b","EventId":{"Id":1,"Name":"UnhandledException"},"SourceContext":"Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware","RequestId":"800000e8-0009-ec00-b63f-84710c7967bb","RequestPath":"/umbraco/backoffice/workflow/actions/approve","ProcessId":89792,"ProcessName":"w3wp","ThreadId":83,"ApplicationId":"6b5d00dc72ce5284e0f562842f9308a3cff85b97","MachineName":"65CP373","Log4NetLevel":"ERROR"},
{"@t":"2024-10-17T05:00:19.5741840Z","@mt":"The response has already started, the error page middleware will not be executed.","@l":"Warning","@tr":"786f13d8abee21f54dbcae439a074e78","@sp":"9dc4005199b28b0b","EventId":{"Id":2,"Name":"ResponseStarted"},"SourceContext":"Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware","RequestId":"800000e8-0009-ec00-b63f-84710c7967bb","RequestPath":"/umbraco/backoffice/workflow/actions/approve","ProcessId":89792,"ProcessName":"w3wp","ThreadId":83,"ApplicationId":"6b5d00dc72ce5284e0f562842f9308a3cff85b97","MachineName":"65CP373","Log4NetLevel":"WARN "},
{"@t":"2024-10-17T05:00:19.5753341Z","@mt":"Connection ID \"{ConnectionId}\", Request ID \"{TraceIdentifier}\": An unhandled exception was thrown by the application.","@l":"Error","@x":"System.InvalidOperationException: There is already an open DataReader associated with this Connection which must be closed first.\r\n   at Microsoft.Data.SqlClient.SqlCommand.ValidateCommand(Boolean isAsync, String method)\r\n   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry, String method)\r\n   at Microsoft.Data.SqlClient.SqlCommand.ExecuteScalar()\r\n   at Umbraco.Cms.Infrastructure.Persistence.FaultHandling.RetryPolicy.ExecuteAction[TResult](Func`1 func)\r\n   at NPoco.Database.ExecuteScalarHelper(DbCommand cmd)\r\n   at NPoco.Database.InsertAsyncImp[T](PocoData pocoData, String tableName, String primaryKeyName, Boolean autoIncrement, T poco, Boolean sync)\r\n   at NPoco.Database.Insert[T](String tableName, String primaryKeyName, Boolean autoIncrement, T poco)\r\n   at NPoco.Database.Insert[T](T poco)\r\n   at Umbraco.Cms.Infrastructure.Persistence.Repositories.Implement.CacheInstructionRepository.Add(CacheInstruction cacheInstruction)\r\n   at Umbraco.Cms.Infrastructure.Services.CacheInstructionService.DeliverInstructionsInBatches(IEnumerable`1 instructions, String localIdentity)\r\n   at Umbraco.Cms.Infrastructure.Sync.BatchedDatabaseServerMessenger.SendMessages()\r\n   at Umbraco.Cms.Core.Events.INotificationHandler`1.Handle(IEnumerable`1 notifications)\r\n   at Umbraco.Cms.Core.Events.EventAggregator.PublishCore[TNotification](IEnumerable`1 allHandlers, IEnumerable`1 notifications)\r\n   at Umbraco.Cms.Core.Events.NotificationHandlerWrapperImpl`1.Handle[TNotification,TNotificationHandler](IEnumerable`1 notifications, ServiceFactory serviceFactory, Action`2 publish)\r\n   at Umbraco.Cms.Core.Events.EventAggregator.PublishNotifications[TNotification,TNotificationHandler](IEnumerable`1 notifications)\r\n   at Umbraco.Cms.Core.Events.EventAggregator.PublishAsync[TNotification,TNotificationHandler](IEnumerable`1 notifications, CancellationToken cancellationToken)\r\n   at Umbraco.Cms.Core.Events.EventAggregator.PublishAsync[TNotification](TNotification notification, CancellationToken cancellationToken)\r\n   at Umbraco.Cms.Web.Common.Middleware.UmbracoRequestMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)\r\n   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.InterfaceMiddlewareBinder.<>c__DisplayClass2_0.<<CreateMiddleware>b__0>d.MoveNext()\r\n--- End of stack trace from previous location ---\r\n   at Umbraco.Cms.Web.Common.Middleware.PreviewAuthenticationMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)\r\n   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.InterfaceMiddlewareBinder.<>c__DisplayClass2_0.<<CreateMiddleware>b__0>d.MoveNext()\r\n--- End of stack trace from previous location ---\r\n   at Umbraco.Cms.Web.Common.Middleware.UmbracoRequestLoggingMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)\r\n   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.InterfaceMiddlewareBinder.<>c__DisplayClass2_0.<<CreateMiddleware>b__0>d.MoveNext()\r\n--- End of stack trace from previous location ---\r\n   at SixLabors.ImageSharp.Web.Middleware.ImageSharpMiddleware.Invoke(HttpContext httpContext, Boolean retry)\r\n   at Umbraco.Forms.Web.HttpModules.ProtectFormUploadRequestsMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)\r\n   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.InterfaceMiddlewareBinder.<>c__DisplayClass2_0.<<CreateMiddleware>b__0>d.MoveNext()\r\n--- End of stack trace from previous location ---\r\n   at Usc.Infrastructure.BackOfficeProtectorMiddleware.Invoke(HttpContext context) in D:\\Git\\CorporateWebsiteV13\\Usc.Infrastructure\\BackOfficeProtectorMiddleware.cs:line 37\r\n   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)\r\n   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)\r\n   at Microsoft.AspNetCore.Server.IIS.Core.IISHttpContextOfT`1.ProcessRequestAsync()","@tr":"786f13d8abee21f54dbcae439a074e78","@sp":"9dc4005199b28b0b","ConnectionId":"17005592233216311527","TraceIdentifier":"800000e8-0009-ec00-b63f-84710c7967bb","EventId":{"Id":2,"Name":"ApplicationError"},"SourceContext":"Microsoft.AspNetCore.Server.IIS.Core.IISHttpServer","RequestId":"800000e8-0009-ec00-b63f-84710c7967bb","RequestPath":"/umbraco/backoffice/workflow/actions/approve","ProcessId":89792,"ProcessName":"w3wp","ThreadId":83,"ApplicationId":"6b5d00dc72ce5284e0f562842f9308a3cff85b97","MachineName":"65CP373","Log4NetLevel":"ERROR"}
]

* Note that from this point on, if you try to Request publish on any further changes made to the page, it will take you to the Request publish panel, allow you to enter a comment and use the Request publish button there, but it then just returns you to the content page, without entering the change into workflow (no messages displayed).

### Expected result

The page is published and the workflow status set to Approved when the workflow is approved.

### Actual result

As above

Thanks,
Bruce

---
_This item has been added to our backlog AB#45084_

**Comment by nathanwoulfe** [comment]
Hey Bruce, this sounds very much related to #79. 

I think I need to have a look at how we manage emailing, and move that logic off to a scheduled task. That way, rather than sending the notifications as part of initiating/processing a workflow process, I'll write to a queue, then pull items from that queue in the hosted service. It's probably more efficient too to send batches of emails every n minutes, rather than sporadically as workflows are actioned. 

I have a release scheduled for next Wednesday, will look at this one tomorrow and should be able to include it, assuming all goes well

**Comment by nathanwoulfe** [comment]
Latest minors include this change - looks to have resolved the problem (at least, I was able to reproduce the bug on a large site, then no longer after adding the email queue).

**Comment by bruceanewton** [comment]
Thanks Nathan, much appreciated.
Bruce
